# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java for more details
#
version: 2
jobs:
  build:
    docker: 
    - image: circleci/openjdk:8-jdk
    - image: circleci/mysql:5.7
      command: [--default-authentication-plugin=mysql_native_password]
      environment:
      - MYSQL_ROOT_PASSWORD: r00tp@ssw0rd
      - MYSQL_DATABASE: stocks
      - MYSQL_USER: monty
      - MYSQL_PASSWORD: m0nty
      
    working_directory: ~/repo
    
    environment:
      MAVEN_OPTS: -Xmx3200m -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true
 
    steps:
    
    - checkout
    
    - run: sudo apt install -y mysql-client
    
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        - v1-dependencies-

    - run: mvn dependency:go-offline
#adding a comment here to poke circleci
    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}

    # run tests!
    - run: mvn integration-test
